apiVersion: v1
kind: Service
metadata:
  name: teste-service
  namespace: teste
spec:
  selector:
    app: teste-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3030
  type: NodePort
