name: Auto PR + Merge de nprd → main

on:
  push:
    branches:
      - nprd

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-pr-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout da branch nprd
        uses: actions/checkout@v3
        with:
          ref: nprd
          fetch-depth: 0

      - name: Configurar Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Criar Pull Request de nprd → main
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: nprd
          title: "Auto PR: nprd → main"
          body: "PR automático gerado por push na branch nprd."
          draft: false
          delete-branch: false
          branch-suffix: timestamp  # evita conflito se PR já existir
          labels: auto-pr

      - name: Habilitar Auto Merge do PR
        if: steps.cpr.outputs.pull-request-number != ''
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
          token: ${{ secrets.GITHUB_TOKEN }}
