name: Auto PR de nprd para main

on:
  push:
    branches:
      - nprd

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch nprd
        uses: actions/checkout@v3
        with:
          ref: nprd

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        id: cpr
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main          # destino
          branch: nprd        # origem
          title: "Auto PR de nprd para main"
          body: "Este PR foi criado automaticamente após push para nprd."
          draft: false

      - name: Espera para garantir visibilidade do PR
        run: sleep 10

      - name: Enable Auto-merge
        uses: peter-evans/enable-pull-request-automerge@v2
        if: steps.cpr.outputs.pull-request-url != ''
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
