name: Auto PR e Merge de nprd → main

on:
  push:
    branches:
      - nprd

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout da branch nprd
        uses: actions/checkout@v3
        with:
          ref: nprd
          fetch-depth: 0  # necessário para criar branches

      - name: Configurar Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Criar nova branch temporária para o PR
        run: |
          git checkout -b tmp-auto-pr-to-main
          git push origin tmp-auto-pr-to-main --force

      - name: Criar Pull Request de tmp-auto-pr-to-main para main
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: tmp-auto-pr-to-main
          title: "Auto PR: nprd → main"
          body: "PR automático criado a partir de push na branch nprd."
          draft: false

      - name: Ativar Auto-Merge
        if: steps.cpr.outputs.pull-request-url != ''
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
