name: Auto PR e Merge de nprd → main

on:
  push:
    branches:
      - nprd

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Criar Pull Request de nprd para main
        id: pr
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "nprd"
          destination_branch: "main"
          pr_title: "Auto PR: nprd → main"
          pr_body: "Este Pull Request foi criado automaticamente após push na branch nprd."
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_label: "auto-pr"
          pr_draft: false

      - name: Esperar 10 segundos para o PR aparecer
        run: sleep 10

      - name: Ativar auto-merge
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
          pull-request-number: ${{ steps.pr.outputs.pr_number }}
